'''
credparser / configure.py

Interactive and non-interactive configuration for credparser settings.

Provides both a programmatic interface and CLI entry point for
customizing salt length and hash round parameters.

Usage:
    As a module:    python -m credparser.configure [OPTIONS]
    As a command:   credparser-config [OPTIONS]
    Programmatic:   from credparser.configure import configure_credparser
'''
import logging
import sys
import argparse
from pathlib import Path

from .credparser import DEFAULT_SEED_FILE
from .config import (
    CREDPARSER_CONFIG_FILE,
    DEFAULT_SALT_LEN,
    DEFAULT_MAX_HASH_ROUNDS,
    DEFAULT_MIN_HASH_ROUNDS,
    LIMIT_MIN_SALT_LEN,
    LIMIT_MIN_HASH_ROUNDS,
    _read_config_file,
    load_config,
)

_logger = logging.getLogger(__name__)


def _write_config_file(
    salt_len: int,
    max_hash_rounds: int,
    min_hash_rounds: int,
    quiet: bool = False
) -> None:
    '''
    Write configuration to credparser config file with validation.

    Args:
        salt_len: Salt length value
        max_hash_rounds: Maximum hash rounds
        min_hash_rounds: Minimum hash rounds
        quiet: If True, suppress output messages

    Raises:
        ValueError: Invalid configuration values
        OSError: File write error
    '''
    # Validate all values using load_config factory
    try:
        load_config(
            salt_len=salt_len,
            max_hash_rounds=max_hash_rounds,
            min_hash_rounds=min_hash_rounds
        )
    except Exception as e:
        raise ValueError(f'Configuration validation failed: {e}')

    _logger.debug(f'Writing config to {CREDPARSER_CONFIG_FILE}')
    config_content = (
        f"# credparser configuration\n"
        f"# Generated by credparser-config\n"
        f"\n"
        f"SALT_LEN = {salt_len}\n"
        f"MAX_HASH_ROUNDS = {max_hash_rounds}\n"
        f"MIN_HASH_ROUNDS = {min_hash_rounds}\n"
    )

    with open(CREDPARSER_CONFIG_FILE, 'w') as f:
        f.write(config_content)

    if not quiet:
        print()
        print(f"Configuration written to: {CREDPARSER_CONFIG_FILE}")
        print()
        print("NOTE: All existing credentials must be regenerated if ")
        print("      any of the values were modified.")

    _logger.debug('Config file written successfully')


def _display_current_config() -> None:
    '''Display current configuration settings.'''
    cfg = load_config()
    print()
    print("Current CredParser Configuration:")
    print("-" * 40)
    print(f"  Salt length:      {cfg.salt_len}")
    print(f"  Min hash rounds:  {cfg.min_hash_rounds}")
    print(f"  Max hash rounds:  {cfg.max_hash_rounds}")
    print(f"  Config file:      {cfg.config_file}")
    print()


def _configure_interactive(
    existing_settings: dict,
    current_salt_len: int,
    current_max_hash: int,
    current_min_hash: int
) -> tuple:
    '''
    Interactive configuration mode.

    Returns:
        Tuple of (salt_len, max_hash_rounds, min_hash_rounds)
    '''
    print('Salt Length')
    print(f'{"=" * 40}')
    print('Salt works as the public key for your credparser credentials.')
    print(f'Salt length must be {LIMIT_MIN_SALT_LEN} or larger.')
    print()

    # Salt length
    salt_input = input(f"Salt length [{current_salt_len}]: ").strip()
    if salt_input:
        salt_len = int(salt_input)
        if salt_len < LIMIT_MIN_SALT_LEN:
            print(f"Error: Salt length must be >= {LIMIT_MIN_SALT_LEN}")
            sys.exit(1)
    else:
        salt_len = current_salt_len

    print()
    print(f'Hashing Rounds')
    print(f'{"=" * 40}')
    print('Hashing rounds are deterministically set using the salt as a seed')
    print('and provide the core encryption/key generation functionality.')
    print('Hash round maximums should optimally be >3x the minimum at least.')
    print()

    # Min hash rounds
    min_hash_input = input(f"Min hash rounds [{current_min_hash}]: ").strip()
    if min_hash_input:
        min_hash_rounds = int(min_hash_input)
        if min_hash_rounds < LIMIT_MIN_HASH_ROUNDS:
            print(f"Error: Min hash rounds must be >= {LIMIT_MIN_HASH_ROUNDS}")
            sys.exit(1)
    else:
        min_hash_rounds = current_min_hash

    # Max hash rounds
    max_hash_input = input(f"Max hash rounds [{current_max_hash}]: ").strip()
    if max_hash_input:
        max_hash_rounds = int(max_hash_input)
    else:
        max_hash_rounds = current_max_hash

    # Validate min <= max
    if min_hash_rounds > max_hash_rounds:
        print("Error: Min hash rounds cannot be greater than max hash rounds")
        sys.exit(1)

    return salt_len, max_hash_rounds, min_hash_rounds


def configure_credparser(
    salt_len: int = None,
    min_hash_rounds: int = None,
    max_hash_rounds: int = None,
    test: bool = False,
    help: bool = False
) -> None:
    '''
    Configure credparser settings interactively or via parameters.

    Allows user to customize salt length and hash round settings.
    Writes configuration to the module's .config file.

    Args:
        salt_len: Salt length (int). If provided with hash rounds, uses
            non-interactive mode.
        min_hash_rounds: Minimum hash rounds (int)
        max_hash_rounds: Maximum hash rounds (int)
        test: If True, validate and display current configuration without modifying
        help: If True, display parameter usage and exit

    Examples:
        Interactive mode (no parameters):
            configure_credparser()

        Non-interactive mode (automated deployment):
            configure_credparser(salt_len=16, min_hash_rounds=10, max_hash_rounds=50)

        Display current configuration:
            configure_credparser(test=True)

        Display help:
            configure_credparser(help=True)
    '''
    if help:
        _print_configure_help()
        return

    if test:
        _logger.debug('Test mode: validating current configuration')
        _display_current_config()
        return

    _logger.debug('Starting configure_credparser')

    # Load existing config values as defaults
    existing_settings = _read_config_file(CREDPARSER_CONFIG_FILE)
    current_salt_len = existing_settings.get('salt_len', DEFAULT_SALT_LEN)
    current_max_hash = existing_settings.get('max_hash_rounds', DEFAULT_MAX_HASH_ROUNDS)
    current_min_hash = existing_settings.get('min_hash_rounds', DEFAULT_MIN_HASH_ROUNDS)

    try:
        # Determine if interactive or non-interactive mode
        if (salt_len is not None
                and min_hash_rounds is not None
                and max_hash_rounds is not None):
            # Non-interactive mode: use provided parameters
            _logger.debug('Non-interactive mode: using provided parameters')
            new_salt_len = salt_len
            new_min_hash = min_hash_rounds
            new_max_hash = max_hash_rounds
            skip_warning = True
        elif salt_len is None and min_hash_rounds is None and max_hash_rounds is None:
            # Interactive mode: prompt user
            _logger.debug('Interactive mode: prompting for input')
            print("CredParser Configuration")
            print("=" * 40)
            print()

            # Check for existing master.seed and warn user
            if DEFAULT_SEED_FILE.exists():
                print("WARNING: A master.seed file exists at:")
                print(f"  {DEFAULT_SEED_FILE}")
                print()
                print("Changing configuration values will cause ALL previously")
                print("encoded credentials to fail decoding.")
                print()
                confirm = input("Continue with configuration? [y/N]: ").strip().lower()
                if confirm != 'y':
                    print("Configuration cancelled.")
                    sys.exit(0)
                print()

            new_salt_len, new_max_hash, new_min_hash = _configure_interactive(
                existing_settings,
                current_salt_len,
                current_max_hash,
                current_min_hash
            )
            skip_warning = False
        else:
            # Partial parameters provided - error
            print(
                "Error: Either provide all three parameters"
                " (salt_len, min_hash_rounds, max_hash_rounds)"
            )
            print("       or provide none for interactive mode")
            sys.exit(1)

        # Display summary
        print()
        print("Configuration Summary:")
        print("-" * 40)
        print(f"  Salt length:      {new_salt_len}")
        print(f"  Min hash rounds:  {new_min_hash}")
        print(f"  Max hash rounds:  {new_max_hash}")
        print(f"  Config file:      {CREDPARSER_CONFIG_FILE}")
        print()

        # Confirm before writing (only in interactive mode)
        if not skip_warning:
            confirm = input("Write configuration? [y/N]: ").strip().lower()
            if confirm != 'y':
                print("Configuration cancelled.")
                sys.exit(0)

        # Write config file
        _write_config_file(new_salt_len, new_max_hash, new_min_hash, quiet=skip_warning)
        _logger.debug('configure_credparser completed successfully')

    except ValueError as e:
        _logger.error(f'Configuration validation error: {e}')
        print(f"Error: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nConfiguration cancelled.")
        sys.exit(1)
    except (OSError, PermissionError) as e:
        _logger.error(f'configure_credparser failed: {e}')
        print(f"Error writing config file: {e}")
        sys.exit(1)


def _print_configure_help() -> None:
    '''Display help information for configure_credparser command.'''
    help_text = '''
CredParser Configuration Tool

Usage:
    credparser-config [OPTIONS]

Options:
    (no options)           Interactive configuration mode
    --help                 Display this help message and exit
    --test                 Validate and display current configuration
    --salt-len INT         Salt length (must be >= 8)
    --min-hash INT         Minimum hash rounds (must be >= 1)
    --max-hash INT         Maximum hash rounds

Non-interactive Mode (Automated Deployment):
    credparser-config --salt-len 16 --min-hash 10 --max-hash 50

    All three parameters are required together for automated mode.
    If only some parameters are provided, interactive mode is used instead.

Configuration Details:
    salt_len:       The salt acts as a public key for credentials.
                    Larger values (16-24) are recommended for production.
                    Minimum: {min_salt}

    min_hash_rounds: Minimum number of key generation hash iterations.
                    Should be at least 1, typically 3-10 for production.
                    Minimum: {min_hash}

    max_hash_rounds: Maximum number of key generation hash iterations.
                    Should be >3x the minimum value.
                    Used for deterministic key stretching.

Environment-Specific Configuration:
    For development:   salt_len=12, min_hash=3, max_hash=24
    For production:    salt_len=16, min_hash=10, max_hash=50
    For high-security: salt_len=20, min_hash=20, max_hash=100

WARNING:
    Changing any configuration values will cause ALL previously
    encoded credentials to fail decoding. Only change values when
    regenerating all credential strings.

Examples:
    # Interactive mode (prompts for values)
    credparser-config

    # Non-interactive mode (for deployment scripts)
    credparser-config --salt-len 16 --min-hash 10 --max-hash 50

    # Display current settings
    credparser-config --test
'''.format(
        min_salt=LIMIT_MIN_SALT_LEN,
        min_hash=LIMIT_MIN_HASH_ROUNDS
    )
    print(help_text)


def configure_credparser_cli() -> None:
    '''
    CLI wrapper for configure_credparser with argument parsing.

    Handles command-line arguments and calls configure_credparser accordingly.
    Entry point for credparser-config command.
    '''
    parser = argparse.ArgumentParser(
        prog='credparser-config',
        description='CredParser configuration tool',
        add_help=False  # Custom help handling
    )

    parser.add_argument(
        '--help',
        action='store_true',
        help='Display help message and exit'
    )

    parser.add_argument(
        '--test',
        action='store_true',
        help='Validate and display current configuration'
    )

    parser.add_argument(
        '--salt-len',
        type=int,
        metavar='INT',
        help='Salt length (must be >= 8)'
    )

    parser.add_argument(
        '--min-hash',
        type=int,
        metavar='INT',
        help='Minimum hash rounds (must be >= 1)'
    )

    parser.add_argument(
        '--max-hash',
        type=int,
        metavar='INT',
        help='Maximum hash rounds'
    )

    try:
        args = parser.parse_args()

        if args.help:
            configure_credparser(help=True)
        elif args.test:
            configure_credparser(test=True)
        elif (args.salt_len is not None
                or args.min_hash is not None
                or args.max_hash is not None):
            # Non-interactive mode
            configure_credparser(
                salt_len=args.salt_len,
                min_hash_rounds=args.min_hash,
                max_hash_rounds=args.max_hash
            )
        else:
            # Interactive mode (no arguments)
            configure_credparser()

    except SystemExit as e:
        # argparse calls sys.exit on error, propagate it
        raise


if __name__ == '__main__':
    configure_credparser_cli()
